# -*- coding: utf-8 -*-
"""Copy of python_systemprogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PhFHEku5p3VxAIFemk5pGfyLum-B_ezA
"""
# """FIFO 예제

# https://gist.github.com/egorps/7695667
# """

import errno
import os, stat
import codecs
import tempfile
import time
#import thread
import _thread

from click import pass_context     #error 2

FIFO_FROM_YOLO = "/tmp/from_yolo_fifo"
FIFO_TO_YOLO = "/tmp/to_yolo_fifo"
fd_from =None
fd_to = None


def t_function(fifo):
   # pass
   #pipein = os.open(fifo_path, os.O_RDWR)

   while True:
      # line = pipein.readline()[:-1]
      line = os.read(fifo, 1 )
      if(line):
         print("receive %s " % (line).decode())



fd_from_yolo = os.open(FIFO_FROM_YOLO, os.O_RDWR)
if fd_from_yolo == -1:
    os.mkfifo(FIFO_FROM_YOLO) 
    fd_from_yolo = os.open(FIFO_FROM_YOLO, os.O_RDWR)

fd_to_yolo = os.open(FIFO_TO_YOLO, os.O_WRONLY)
if fd_to_yolo == -1:
    os.mkfifo(FIFO_TO_YOLO) 
    fd_to_yolo = os.open(FIFO_TO_YOLO, os.O_WRONLY)


_thread.start_new_thread(t_function, (fd_from_yolo,))    # error 2      
   
count = 0
while True:
    message = "%d" % count
    # print("================== ")
    print("Writing ", message)
    # os.write(fd_to_yolo, "%s" % ( message))
    # os.write(fd_to_yolo, "%d" % ( count))

    #os.write(pipe, "aaaaaaaaaa".encode())  # error 3
    # os.write(fd_to_yolo, ("%s" % (message)).encode())
    os.write(fd_to_yolo, ("%s" % (count)).encode())
    count += 1
    time.sleep(1)
    if(count == 100):
        count = 0


